linters:
  enable:
    - bodyclose
    - errcheck
    - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - testifylint
    - typecheck
    - unconvert
    - unused
    - wsl