linters:
  enable:
    - bodyclose
    - decorder
    - errcheck
    - errname
    - errorlint
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoglobals
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goheader
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nestif
    - nilerr
    - nilnil
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - testifylint
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - wsl
    - zerologlint