linters:
  enable:
    - bidichk
    - bodyclose
    - decorder
    - err113
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goheader
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - ineffassign
    - intrange
    - lll
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - reassign
    - revive
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - wsl
    - zerologlint