name: go-test
on:
  push:
    tags:
      - 'v*'
    branches:
      - '*'
  pull_request:
permissions:
  contents: read
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: false
      - uses: actions/checkout@v3
      - run: go test -v -race ./...